name: Deploy Xplorers Bot to Google Cloud

on:
  push:
    branches:
      - main
jobs:
  deploy-xplorers-bot-to-gcp:
    runs-on: ubuntu-latest
    # ...

    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write

    steps:
    # actions/checkout MUST come before auth
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP_SERVICE_ACCOUNT }}
        token_format: access_token
        create_credentials_file: true
        access_token_lifetime: 120s

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: deploy
      name: Deploy XplorersBot
      run: |-
        make apply
