name: Run CI Tests

on: push

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install taskfile
      run: |
        sudo snap install task --classic

    - id: run-unit-tests
      name: Run unit tests
      run: task install && task test
